security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
      
git-property-test: this property from git

sprx:
  configurationName: my configuration
  token: ENC(ILHkFvHwUIb38/ZmlSLXjoLE1qq3wWg54A7IfOYTszqrxuu2tD/JFHksuCFfCR9DSZbgweRSCF4=)
