security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
      
qais: pcf-test

sprx:
  configurationName: my configuration
  token: ENC(eD4k72SDLnIleih1dSUTEH7FAqwlp2Nb)
